DevEx-547: Support custom log output via logback
giffgaff/gg-wiremock pull request #2
Opened 2023-11-13 11:58 UTC by LukeKynaston

### Status
READY

### Jira Task
https://giffgaff.atlassian.net/browse/DEVEX-547

### Related PRs
https://github.com/giffgaff/mock-server/pull/9

### Changes
Wiremock defaults to using SLF4J with Logback, with the same logging output as before this change. This also applies to verbose logging.

When using the `logback-config-file` CLI parameter we can pick up and use a specified logback file instead.

2023-11-13 16:41 UTC, jazdeol1 requested changes

2023-11-13 16:41 UTC, jazdeol1 commented on src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
> +  }
Is this test correct, looks the same as the one above minus the file being passed into the command line options.

2023-11-13 18:05 UTC, LukeKynaston commented on src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
> +  }
Yeah, my bad.

2023-11-16 10:50 UTC, jazdeol1 approved these changes

2023-11-17 16:26 UTC, kelseyh requested changes

2023-11-17 16:26 UTC, kelseyh commented on src/main/java/com/github/tomakehurst/wiremock/common/Slf4jNotifier.java
> +    }
doesn't the cmdline handler print this out on startup anyway? think we can remove

2023-11-17 16:26 UTC, kelseyh commented on src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
> +  private void addSlf4JFileToClasspath() {
needs to be renamed

2023-11-17 16:26 UTC, kelseyh commented on src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
> +            "example.com")
let's not format this, less noise if we submit as a PR for wiremock

2023-11-17 16:26 UTC, kelseyh commented on src/test/resources/logback-test.xml
seems to be the same as the default one so we shouldn't need it

2023-11-20 12:29 UTC, LukeKynaston commented on src/main/java/com/github/tomakehurst/wiremock/common/Slf4jNotifier.java
> +    }
Yeah it does, but that's in the `ConsoleNotifier`. We're using the `Slf4jNotifier` in this change.

2023-11-21 14:24 UTC, kelseyh requested changes

2023-11-21 14:24 UTC, kelseyh commented on src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
> +
setLogbackConfigurationFile does the exact same check?

2023-11-21 14:24 UTC, kelseyh commented on src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
> +    setLogbackConfigurationFile();
shouldn't this be `configureLogbackIfRequested()` to follow the convention?

2023-11-21 15:05 UTC, LukeKynaston commented on src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
> +
I've called this method now instead of duplicating the check.

2023-11-22 16:01 UTC, kelseyh approved these changes

2023-11-22 16:01 UTC, merged